name: macro_builder
publish_to: 'none'

environment:
  sdk: ^3.0.0

dependencies:
  analyzer: ^7.4.5
  build: ^2.2.1
  code_builder: ^4.1.0
  dart_style: ^3.0.1
  glob: ^2.0.2
  path: ^1.8.1

dev_dependencies:
  lints: ^6.0.0
