name: BSD

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  ffigen:
    if: ${{true}}
    runs-on: macos-15
    steps:
    - uses: actions/checkout@v4
    - uses: dart-lang/setup-dart@v1
    - run: dart pub get
    - run: dart run ffigen --config lib/src/bsd/ffigen.yaml
    - uses: peter-evans/create-pull-request@v7
      if: github.event_name != 'pull_request'
      with:
        title: 'Regenerate BSD bindings'
        commit-message: 'Regenerate BSD bindings'
        add-paths: lib/src/bsd/ffigen.dart
        branch: regenerate/bsd
        delete-branch: true
    - uses: actions/upload-artifact@v4
      with:
        name: ffigen.dart
        path: lib/src/bsd/ffigen.dart
    - run: |
        git diff > lib_src_bsd_ffigen.dart.diff
        [ -s lib_src_bsd_ffigen.dart.diff ] || rm lib_src_bsd_ffigen.dart.diff
    - uses: actions/upload-artifact@v4
      with:
        name: lib_src_bsd_ffigen.dart.diff
        path: lib_src_bsd_ffigen.dart.diff
        if-no-files-found: ignore
    - run: ./.github/scripts/check-outdated-files.sh
